#!/bin/sh

if [ -x /usr/bin/padsp ]; then
    exec /usr/bin/padsp /usr/bin/theora_player.bin "$@"
else
    # This is unlikely to work since we don't load the OSS compat drivers
    # by default.  Install pulseaudio-utils.
    exec /usr/bin/theora_player.bin "$@"
fi
